/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPostsDotxmlRouteImport } from './routes/sitemap-posts[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiSiteRouteImport } from './routes/api/site'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiPagesRouteImport } from './routes/api/pages'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiBackupsRouteImport } from './routes/api/backups'
import { Route as ApiAssetsRouteImport } from './routes/api/assets'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as ZhDocsSplatRouteImport } from './routes/zh/docs/$'
import { Route as ApiPostsBatchRouteImport } from './routes/api/posts/batch'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts/$id'
import { Route as ApiPagesIdRouteImport } from './routes/api/pages/$id'
import { Route as ApiImportZipRouteImport } from './routes/api/import/zip'
import { Route as ApiImportMarkdownRouteImport } from './routes/api/import/markdown'
import { Route as ApiImportHtmlRouteImport } from './routes/api/import/html'
import { Route as ApiCommentAuthVerifyEmailRouteImport } from './routes/api/comment-auth/verify-email'
import { Route as ApiCommentAuthSignupRouteImport } from './routes/api/comment-auth/signup'
import { Route as ApiCommentAuthMeRouteImport } from './routes/api/comment-auth/me'
import { Route as ApiCommentAuthLogoutRouteImport } from './routes/api/comment-auth/logout'
import { Route as ApiCommentAuthLoginRouteImport } from './routes/api/comment-auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsIdRouteImport } from './routes/api/assets/$id'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminPasswordResetRouteImport } from './routes/api/admin/password-reset'
import { Route as ApiAdminPasswordRouteImport } from './routes/api/admin/password'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminEmailStatusRouteImport } from './routes/api/admin/email-status'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth/admin/settings'
import { Route as AuthAdminPostsRouteImport } from './routes/_auth/admin/posts'
import { Route as AuthAdminPagesRouteImport } from './routes/_auth/admin/pages'
import { Route as AuthAdminCommentsRouteImport } from './routes/_auth/admin/comments'
import { Route as AuthAdminAssetsRouteImport } from './routes/_auth/admin/assets'
import { Route as ApiTokensIdRevokeRouteImport } from './routes/api/tokens/$id/revoke'
import { Route as ApiCommentsIdSpamRouteImport } from './routes/api/comments/$id/spam'
import { Route as ApiCommentsIdDeleteRouteImport } from './routes/api/comments/$id/delete'
import { Route as ApiCommentsIdApproveRouteImport } from './routes/api/comments/$id/approve'
import { Route as ApiCommentAuthGithubStartRouteImport } from './routes/api/comment-auth/github/start'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPostsDotxmlRoute = SitemapPostsDotxmlRouteImport.update({
  id: '/sitemap-posts.xml',
  path: '/sitemap-posts.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteRoute = ApiSiteRouteImport.update({
  id: '/api/site',
  path: '/api/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesRoute = ApiPagesRouteImport.update({
  id: '/api/pages',
  path: '/api/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupsRoute = ApiBackupsRouteImport.update({
  id: '/api/backups',
  path: '/api/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ZhDocsSplatRoute = ZhDocsSplatRouteImport.update({
  id: '/zh/docs/$',
  path: '/zh/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsBatchRoute = ApiPostsBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiPagesIdRoute = ApiPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPagesRoute,
} as any)
const ApiImportZipRoute = ApiImportZipRouteImport.update({
  id: '/api/import/zip',
  path: '/api/import/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportMarkdownRoute = ApiImportMarkdownRouteImport.update({
  id: '/api/import/markdown',
  path: '/api/import/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportHtmlRoute = ApiImportHtmlRouteImport.update({
  id: '/api/import/html',
  path: '/api/import/html',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthVerifyEmailRoute =
  ApiCommentAuthVerifyEmailRouteImport.update({
    id: '/api/comment-auth/verify-email',
    path: '/api/comment-auth/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommentAuthSignupRoute = ApiCommentAuthSignupRouteImport.update({
  id: '/api/comment-auth/signup',
  path: '/api/comment-auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthMeRoute = ApiCommentAuthMeRouteImport.update({
  id: '/api/comment-auth/me',
  path: '/api/comment-auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthLogoutRoute = ApiCommentAuthLogoutRouteImport.update({
  id: '/api/comment-auth/logout',
  path: '/api/comment-auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthLoginRoute = ApiCommentAuthLoginRouteImport.update({
  id: '/api/comment-auth/login',
  path: '/api/comment-auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsIdRoute = ApiAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAssetsRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordResetRoute = ApiAdminPasswordResetRouteImport.update({
  id: '/api/admin/password-reset',
  path: '/api/admin/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordRoute = ApiAdminPasswordRouteImport.update({
  id: '/api/admin/password',
  path: '/api/admin/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailStatusRoute = ApiAdminEmailStatusRouteImport.update({
  id: '/api/admin/email-status',
  path: '/api/admin/email-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPostsRoute = AuthAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPagesRoute = AuthAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminCommentsRoute = AuthAdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminAssetsRoute = AuthAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ApiTokensIdRevokeRoute = ApiTokensIdRevokeRouteImport.update({
  id: '/$id/revoke',
  path: '/$id/revoke',
  getParentRoute: () => ApiTokensRoute,
} as any)
const ApiCommentsIdSpamRoute = ApiCommentsIdSpamRouteImport.update({
  id: '/$id/spam',
  path: '/$id/spam',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsIdDeleteRoute = ApiCommentsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsIdApproveRoute = ApiCommentsIdApproveRouteImport.update({
  id: '/$id/approve',
  path: '/$id/approve',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentAuthGithubStartRoute =
  ApiCommentAuthGithubStartRouteImport.update({
    id: '/api/comment-auth/github/start',
    path: '/api/comment-auth/github/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/admin/assets': typeof AuthAdminAssetsRoute
  '/admin/comments': typeof AuthAdminCommentsRoute
  '/admin/pages': typeof AuthAdminPagesRoute
  '/admin/posts': typeof AuthAdminPostsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/pages/$id': typeof ApiPagesIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/app/': typeof AuthAppIndexRoute
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/tags': typeof TagsIndexRoute
  '/admin/assets': typeof AuthAdminAssetsRoute
  '/admin/comments': typeof AuthAdminCommentsRoute
  '/admin/pages': typeof AuthAdminPagesRoute
  '/admin/posts': typeof AuthAdminPostsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/pages/$id': typeof ApiPagesIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/admin': typeof AuthAdminIndexRoute
  '/app': typeof AuthAppIndexRoute
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/_auth/admin/assets': typeof AuthAdminAssetsRoute
  '/_auth/admin/comments': typeof AuthAdminCommentsRoute
  '/_auth/admin/pages': typeof AuthAdminPagesRoute
  '/_auth/admin/posts': typeof AuthAdminPostsRoute
  '/_auth/admin/settings': typeof AuthAdminSettingsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/pages/$id': typeof ApiPagesIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/pages'
    | '/api/posts'
    | '/api/search'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog/'
    | '/tags/'
    | '/admin/assets'
    | '/admin/comments'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/pages/$id'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/zh/docs/$'
    | '/admin/'
    | '/app/'
    | '/api/comment-auth/github/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/pages'
    | '/api/posts'
    | '/api/search'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog'
    | '/tags'
    | '/admin/assets'
    | '/admin/comments'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/pages/$id'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/zh/docs/$'
    | '/admin'
    | '/app'
    | '/api/comment-auth/github/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/_auth/admin'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_guest/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/pages'
    | '/api/posts'
    | '/api/search'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog/'
    | '/tags/'
    | '/_auth/admin/assets'
    | '/_auth/admin/comments'
    | '/_auth/admin/pages'
    | '/_auth/admin/posts'
    | '/_auth/admin/settings'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/pages/$id'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/zh/docs/$'
    | '/_auth/admin/'
    | '/_auth/app/'
    | '/api/comment-auth/github/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapPostsDotxmlRoute: typeof SitemapPostsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAssetsRoute: typeof ApiAssetsRouteWithChildren
  ApiBackupsRoute: typeof ApiBackupsRoute
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  ApiPagesRoute: typeof ApiPagesRouteWithChildren
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSiteRoute: typeof ApiSiteRoute
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  TagsSlugRoute: typeof TagsSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ApiAdminEmailStatusRoute: typeof ApiAdminEmailStatusRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminPasswordRoute: typeof ApiAdminPasswordRoute
  ApiAdminPasswordResetRoute: typeof ApiAdminPasswordResetRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommentAuthLoginRoute: typeof ApiCommentAuthLoginRoute
  ApiCommentAuthLogoutRoute: typeof ApiCommentAuthLogoutRoute
  ApiCommentAuthMeRoute: typeof ApiCommentAuthMeRoute
  ApiCommentAuthSignupRoute: typeof ApiCommentAuthSignupRoute
  ApiCommentAuthVerifyEmailRoute: typeof ApiCommentAuthVerifyEmailRoute
  ApiImportHtmlRoute: typeof ApiImportHtmlRoute
  ApiImportMarkdownRoute: typeof ApiImportMarkdownRoute
  ApiImportZipRoute: typeof ApiImportZipRoute
  ZhDocsSplatRoute: typeof ZhDocsSplatRoute
  ApiCommentAuthGithubStartRoute: typeof ApiCommentAuthGithubStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-posts.xml': {
      id: '/sitemap-posts.xml'
      path: '/sitemap-posts.xml'
      fullPath: '/sitemap-posts.xml'
      preLoaderRoute: typeof SitemapPostsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site': {
      id: '/api/site'
      path: '/api/site'
      fullPath: '/api/site'
      preLoaderRoute: typeof ApiSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages': {
      id: '/api/pages'
      path: '/api/pages'
      fullPath: '/api/pages'
      preLoaderRoute: typeof ApiPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backups': {
      id: '/api/backups'
      path: '/api/backups'
      fullPath: '/api/backups'
      preLoaderRoute: typeof ApiBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/zh/docs/$': {
      id: '/zh/docs/$'
      path: '/zh/docs/$'
      fullPath: '/zh/docs/$'
      preLoaderRoute: typeof ZhDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/batch': {
      id: '/api/posts/batch'
      path: '/batch'
      fullPath: '/api/posts/batch'
      preLoaderRoute: typeof ApiPostsBatchRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/pages/$id': {
      id: '/api/pages/$id'
      path: '/$id'
      fullPath: '/api/pages/$id'
      preLoaderRoute: typeof ApiPagesIdRouteImport
      parentRoute: typeof ApiPagesRoute
    }
    '/api/import/zip': {
      id: '/api/import/zip'
      path: '/api/import/zip'
      fullPath: '/api/import/zip'
      preLoaderRoute: typeof ApiImportZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/markdown': {
      id: '/api/import/markdown'
      path: '/api/import/markdown'
      fullPath: '/api/import/markdown'
      preLoaderRoute: typeof ApiImportMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/html': {
      id: '/api/import/html'
      path: '/api/import/html'
      fullPath: '/api/import/html'
      preLoaderRoute: typeof ApiImportHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/verify-email': {
      id: '/api/comment-auth/verify-email'
      path: '/api/comment-auth/verify-email'
      fullPath: '/api/comment-auth/verify-email'
      preLoaderRoute: typeof ApiCommentAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/signup': {
      id: '/api/comment-auth/signup'
      path: '/api/comment-auth/signup'
      fullPath: '/api/comment-auth/signup'
      preLoaderRoute: typeof ApiCommentAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/me': {
      id: '/api/comment-auth/me'
      path: '/api/comment-auth/me'
      fullPath: '/api/comment-auth/me'
      preLoaderRoute: typeof ApiCommentAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/logout': {
      id: '/api/comment-auth/logout'
      path: '/api/comment-auth/logout'
      fullPath: '/api/comment-auth/logout'
      preLoaderRoute: typeof ApiCommentAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/login': {
      id: '/api/comment-auth/login'
      path: '/api/comment-auth/login'
      fullPath: '/api/comment-auth/login'
      preLoaderRoute: typeof ApiCommentAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdRouteImport
      parentRoute: typeof ApiAssetsRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password-reset': {
      id: '/api/admin/password-reset'
      path: '/api/admin/password-reset'
      fullPath: '/api/admin/password-reset'
      preLoaderRoute: typeof ApiAdminPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password': {
      id: '/api/admin/password'
      path: '/api/admin/password'
      fullPath: '/api/admin/password'
      preLoaderRoute: typeof ApiAdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-status': {
      id: '/api/admin/email-status'
      path: '/api/admin/email-status'
      fullPath: '/api/admin/email-status'
      preLoaderRoute: typeof ApiAdminEmailStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/settings': {
      id: '/_auth/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/posts': {
      id: '/_auth/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthAdminPostsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/pages': {
      id: '/_auth/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthAdminPagesRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/comments': {
      id: '/_auth/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthAdminCommentsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/assets': {
      id: '/_auth/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthAdminAssetsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/api/tokens/$id/revoke': {
      id: '/api/tokens/$id/revoke'
      path: '/$id/revoke'
      fullPath: '/api/tokens/$id/revoke'
      preLoaderRoute: typeof ApiTokensIdRevokeRouteImport
      parentRoute: typeof ApiTokensRoute
    }
    '/api/comments/$id/spam': {
      id: '/api/comments/$id/spam'
      path: '/$id/spam'
      fullPath: '/api/comments/$id/spam'
      preLoaderRoute: typeof ApiCommentsIdSpamRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/$id/delete': {
      id: '/api/comments/$id/delete'
      path: '/$id/delete'
      fullPath: '/api/comments/$id/delete'
      preLoaderRoute: typeof ApiCommentsIdDeleteRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/$id/approve': {
      id: '/api/comments/$id/approve'
      path: '/$id/approve'
      fullPath: '/api/comments/$id/approve'
      preLoaderRoute: typeof ApiCommentsIdApproveRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comment-auth/github/start': {
      id: '/api/comment-auth/github/start'
      path: '/api/comment-auth/github/start'
      fullPath: '/api/comment-auth/github/start'
      preLoaderRoute: typeof ApiCommentAuthGithubStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminAssetsRoute: typeof AuthAdminAssetsRoute
  AuthAdminCommentsRoute: typeof AuthAdminCommentsRoute
  AuthAdminPagesRoute: typeof AuthAdminPagesRoute
  AuthAdminPostsRoute: typeof AuthAdminPostsRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminAssetsRoute: AuthAdminAssetsRoute,
  AuthAdminCommentsRoute: AuthAdminCommentsRoute,
  AuthAdminPagesRoute: AuthAdminPagesRoute,
  AuthAdminPostsRoute: AuthAdminPostsRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiAssetsRouteChildren {
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
}

const ApiAssetsRouteChildren: ApiAssetsRouteChildren = {
  ApiAssetsIdRoute: ApiAssetsIdRoute,
}

const ApiAssetsRouteWithChildren = ApiAssetsRoute._addFileChildren(
  ApiAssetsRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsIdApproveRoute: typeof ApiCommentsIdApproveRoute
  ApiCommentsIdDeleteRoute: typeof ApiCommentsIdDeleteRoute
  ApiCommentsIdSpamRoute: typeof ApiCommentsIdSpamRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsIdApproveRoute: ApiCommentsIdApproveRoute,
  ApiCommentsIdDeleteRoute: ApiCommentsIdDeleteRoute,
  ApiCommentsIdSpamRoute: ApiCommentsIdSpamRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiPagesRouteChildren {
  ApiPagesIdRoute: typeof ApiPagesIdRoute
}

const ApiPagesRouteChildren: ApiPagesRouteChildren = {
  ApiPagesIdRoute: ApiPagesIdRoute,
}

const ApiPagesRouteWithChildren = ApiPagesRoute._addFileChildren(
  ApiPagesRouteChildren,
)

interface ApiPostsRouteChildren {
  ApiPostsIdRoute: typeof ApiPostsIdRoute
  ApiPostsBatchRoute: typeof ApiPostsBatchRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsIdRoute: ApiPostsIdRoute,
  ApiPostsBatchRoute: ApiPostsBatchRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

interface ApiTokensRouteChildren {
  ApiTokensIdRevokeRoute: typeof ApiTokensIdRevokeRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensIdRevokeRoute: ApiTokensIdRevokeRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapPostsDotxmlRoute: SitemapPostsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAssetsRoute: ApiAssetsRouteWithChildren,
  ApiBackupsRoute: ApiBackupsRoute,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  ApiPagesRoute: ApiPagesRouteWithChildren,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSiteRoute: ApiSiteRoute,
  ApiTokensRoute: ApiTokensRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  TagsSlugRoute: TagsSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  ApiAdminEmailStatusRoute: ApiAdminEmailStatusRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminPasswordRoute: ApiAdminPasswordRoute,
  ApiAdminPasswordResetRoute: ApiAdminPasswordResetRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommentAuthLoginRoute: ApiCommentAuthLoginRoute,
  ApiCommentAuthLogoutRoute: ApiCommentAuthLogoutRoute,
  ApiCommentAuthMeRoute: ApiCommentAuthMeRoute,
  ApiCommentAuthSignupRoute: ApiCommentAuthSignupRoute,
  ApiCommentAuthVerifyEmailRoute: ApiCommentAuthVerifyEmailRoute,
  ApiImportHtmlRoute: ApiImportHtmlRoute,
  ApiImportMarkdownRoute: ApiImportMarkdownRoute,
  ApiImportZipRoute: ApiImportZipRoute,
  ZhDocsSplatRoute: ZhDocsSplatRoute,
  ApiCommentAuthGithubStartRoute: ApiCommentAuthGithubStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
