/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPostsDotxmlRouteImport } from './routes/sitemap-posts[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'
import { Route as SeriesSlugRouteImport } from './routes/series/$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiSiteRouteImport } from './routes/api/site'
import { Route as ApiSeriesRouteImport } from './routes/api/series'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiBackupsRouteImport } from './routes/api/backups'
import { Route as ApiAssetsRouteImport } from './routes/api/assets'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as ZhDocsSplatRouteImport } from './routes/zh/docs/$'
import { Route as ApiSyncObsidianRouteImport } from './routes/api/sync/obsidian'
import { Route as ApiSeriesIdRouteImport } from './routes/api/series/$id'
import { Route as ApiPostsBatchRouteImport } from './routes/api/posts/batch'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts/$id'
import { Route as ApiImportZipRouteImport } from './routes/api/import/zip'
import { Route as ApiImportMarkdownRouteImport } from './routes/api/import/markdown'
import { Route as ApiImportHtmlRouteImport } from './routes/api/import/html'
import { Route as ApiEmailUnsubscribeRouteImport } from './routes/api/email/unsubscribe'
import { Route as ApiCommentAuthVerifyEmailRouteImport } from './routes/api/comment-auth/verify-email'
import { Route as ApiCommentAuthSignupRouteImport } from './routes/api/comment-auth/signup'
import { Route as ApiCommentAuthMeRouteImport } from './routes/api/comment-auth/me'
import { Route as ApiCommentAuthLogoutRouteImport } from './routes/api/comment-auth/logout'
import { Route as ApiCommentAuthLoginRouteImport } from './routes/api/comment-auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsIdRouteImport } from './routes/api/assets/$id'
import { Route as ApiAnalyticsTrackRouteImport } from './routes/api/analytics/track'
import { Route as ApiAnalyticsOverviewRouteImport } from './routes/api/analytics/overview'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminPasswordResetRouteImport } from './routes/api/admin/password-reset'
import { Route as ApiAdminPasswordRouteImport } from './routes/api/admin/password'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminEmailStatusRouteImport } from './routes/api/admin/email-status'
import { Route as ApiAdminEmailBroadcastsRouteImport } from './routes/api/admin/email-broadcasts'
import { Route as ApiAdminAiSettingsRouteImport } from './routes/api/admin/ai-settings'
import { Route as ApiAccountVerificationEmailRouteImport } from './routes/api/account/verification-email'
import { Route as ApiAccountSignupRouteImport } from './routes/api/account/signup'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAccountPasswordResetRouteImport } from './routes/api/account/password-reset'
import { Route as ApiAccountPasswordRouteImport } from './routes/api/account/password'
import { Route as ApiAccountMeRouteImport } from './routes/api/account/me'
import { Route as ApiAccountLogoutRouteImport } from './routes/api/account/logout'
import { Route as ApiAccountLoginRouteImport } from './routes/api/account/login'
import { Route as ApiAccountEmailPreferencesRouteImport } from './routes/api/account/email-preferences'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth/admin/settings'
import { Route as AuthAdminSeriesRouteImport } from './routes/_auth/admin/series'
import { Route as AuthAdminPostsRouteImport } from './routes/_auth/admin/posts'
import { Route as AuthAdminCommentsRouteImport } from './routes/_auth/admin/comments'
import { Route as AuthAdminAssetsRouteImport } from './routes/_auth/admin/assets'
import { Route as AuthAdminPostsIndexRouteImport } from './routes/_auth/admin/posts/index'
import { Route as ApiTokensIdRevokeRouteImport } from './routes/api/tokens/$id/revoke'
import { Route as ApiCommentsIdSpamRouteImport } from './routes/api/comments/$id/spam'
import { Route as ApiCommentsIdDeleteRouteImport } from './routes/api/comments/$id/delete'
import { Route as ApiCommentsIdApproveRouteImport } from './routes/api/comments/$id/approve'
import { Route as ApiCommentAuthGoogleStartRouteImport } from './routes/api/comment-auth/google/start'
import { Route as ApiCommentAuthGithubStartRouteImport } from './routes/api/comment-auth/github/start'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminAiSettingsTestRouteImport } from './routes/api/admin/ai-settings/test'
import { Route as ApiAdminAiSettingsApiKeyRouteImport } from './routes/api/admin/ai-settings/api-key'
import { Route as AuthAdminPostsNewRouteImport } from './routes/_auth/admin/posts/new'
import { Route as AuthAdminPostsPostIdRouteImport } from './routes/_auth/admin/posts/$postId'
import { Route as ApiAdminUsersIdSessionsRouteImport } from './routes/api/admin/users/$id/sessions'
import { Route as ApiAdminUsersIdPasswordResetRouteImport } from './routes/api/admin/users/$id/password-reset'
import { Route as ApiAdminLoginSocialCompleteRouteImport } from './routes/api/admin/login/social/complete'
import { Route as ApiAdminLoginProviderStartRouteImport } from './routes/api/admin/login/$provider/start'
import { Route as ApiAccountLoginSocialCompleteRouteImport } from './routes/api/account/login/social/complete'
import { Route as ApiAccountLoginProviderStartRouteImport } from './routes/api/account/login/$provider/start'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPostsDotxmlRoute = SitemapPostsDotxmlRouteImport.update({
  id: '/sitemap-posts.xml',
  path: '/sitemap-posts.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/$.lazy').then((d) => d.Route))
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteRoute = ApiSiteRouteImport.update({
  id: '/api/site',
  path: '/api/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupsRoute = ApiBackupsRouteImport.update({
  id: '/api/backups',
  path: '/api/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ZhDocsSplatRoute = ZhDocsSplatRouteImport.update({
  id: '/zh/docs/$',
  path: '/zh/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/zh/docs/$.lazy').then((d) => d.Route))
const ApiSyncObsidianRoute = ApiSyncObsidianRouteImport.update({
  id: '/api/sync/obsidian',
  path: '/api/sync/obsidian',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesIdRoute = ApiSeriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSeriesRoute,
} as any)
const ApiPostsBatchRoute = ApiPostsBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiImportZipRoute = ApiImportZipRouteImport.update({
  id: '/api/import/zip',
  path: '/api/import/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportMarkdownRoute = ApiImportMarkdownRouteImport.update({
  id: '/api/import/markdown',
  path: '/api/import/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportHtmlRoute = ApiImportHtmlRouteImport.update({
  id: '/api/import/html',
  path: '/api/import/html',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailUnsubscribeRoute = ApiEmailUnsubscribeRouteImport.update({
  id: '/api/email/unsubscribe',
  path: '/api/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthVerifyEmailRoute =
  ApiCommentAuthVerifyEmailRouteImport.update({
    id: '/api/comment-auth/verify-email',
    path: '/api/comment-auth/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommentAuthSignupRoute = ApiCommentAuthSignupRouteImport.update({
  id: '/api/comment-auth/signup',
  path: '/api/comment-auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthMeRoute = ApiCommentAuthMeRouteImport.update({
  id: '/api/comment-auth/me',
  path: '/api/comment-auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthLogoutRoute = ApiCommentAuthLogoutRouteImport.update({
  id: '/api/comment-auth/logout',
  path: '/api/comment-auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentAuthLoginRoute = ApiCommentAuthLoginRouteImport.update({
  id: '/api/comment-auth/login',
  path: '/api/comment-auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsIdRoute = ApiAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAssetsRoute,
} as any)
const ApiAnalyticsTrackRoute = ApiAnalyticsTrackRouteImport.update({
  id: '/api/analytics/track',
  path: '/api/analytics/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsOverviewRoute = ApiAnalyticsOverviewRouteImport.update({
  id: '/api/analytics/overview',
  path: '/api/analytics/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordResetRoute = ApiAdminPasswordResetRouteImport.update({
  id: '/api/admin/password-reset',
  path: '/api/admin/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordRoute = ApiAdminPasswordRouteImport.update({
  id: '/api/admin/password',
  path: '/api/admin/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailStatusRoute = ApiAdminEmailStatusRouteImport.update({
  id: '/api/admin/email-status',
  path: '/api/admin/email-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailBroadcastsRoute = ApiAdminEmailBroadcastsRouteImport.update({
  id: '/api/admin/email-broadcasts',
  path: '/api/admin/email-broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiSettingsRoute = ApiAdminAiSettingsRouteImport.update({
  id: '/api/admin/ai-settings',
  path: '/api/admin/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountVerificationEmailRoute =
  ApiAccountVerificationEmailRouteImport.update({
    id: '/api/account/verification-email',
    path: '/api/account/verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountSignupRoute = ApiAccountSignupRouteImport.update({
  id: '/api/account/signup',
  path: '/api/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountPasswordResetRoute = ApiAccountPasswordResetRouteImport.update({
  id: '/api/account/password-reset',
  path: '/api/account/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountPasswordRoute = ApiAccountPasswordRouteImport.update({
  id: '/api/account/password',
  path: '/api/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountMeRoute = ApiAccountMeRouteImport.update({
  id: '/api/account/me',
  path: '/api/account/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountLogoutRoute = ApiAccountLogoutRouteImport.update({
  id: '/api/account/logout',
  path: '/api/account/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountLoginRoute = ApiAccountLoginRouteImport.update({
  id: '/api/account/login',
  path: '/api/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountEmailPreferencesRoute =
  ApiAccountEmailPreferencesRouteImport.update({
    id: '/api/account/email-preferences',
    path: '/api/account/email-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminSeriesRoute = AuthAdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPostsRoute = AuthAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminCommentsRoute = AuthAdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminAssetsRoute = AuthAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPostsIndexRoute = AuthAdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminPostsRoute,
} as any)
const ApiTokensIdRevokeRoute = ApiTokensIdRevokeRouteImport.update({
  id: '/$id/revoke',
  path: '/$id/revoke',
  getParentRoute: () => ApiTokensRoute,
} as any)
const ApiCommentsIdSpamRoute = ApiCommentsIdSpamRouteImport.update({
  id: '/$id/spam',
  path: '/$id/spam',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsIdDeleteRoute = ApiCommentsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsIdApproveRoute = ApiCommentsIdApproveRouteImport.update({
  id: '/$id/approve',
  path: '/$id/approve',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentAuthGoogleStartRoute =
  ApiCommentAuthGoogleStartRouteImport.update({
    id: '/api/comment-auth/google/start',
    path: '/api/comment-auth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommentAuthGithubStartRoute =
  ApiCommentAuthGithubStartRouteImport.update({
    id: '/api/comment-auth/github/start',
    path: '/api/comment-auth/github/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminAiSettingsTestRoute = ApiAdminAiSettingsTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiAdminAiSettingsRoute,
} as any)
const ApiAdminAiSettingsApiKeyRoute =
  ApiAdminAiSettingsApiKeyRouteImport.update({
    id: '/api-key',
    path: '/api-key',
    getParentRoute: () => ApiAdminAiSettingsRoute,
  } as any)
const AuthAdminPostsNewRoute = AuthAdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAdminPostsRoute,
} as any)
const AuthAdminPostsPostIdRoute = AuthAdminPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthAdminPostsRoute,
} as any)
const ApiAdminUsersIdSessionsRoute = ApiAdminUsersIdSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminUsersIdPasswordResetRoute =
  ApiAdminUsersIdPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => ApiAdminUsersIdRoute,
  } as any)
const ApiAdminLoginSocialCompleteRoute =
  ApiAdminLoginSocialCompleteRouteImport.update({
    id: '/social/complete',
    path: '/social/complete',
    getParentRoute: () => ApiAdminLoginRoute,
  } as any)
const ApiAdminLoginProviderStartRoute =
  ApiAdminLoginProviderStartRouteImport.update({
    id: '/$provider/start',
    path: '/$provider/start',
    getParentRoute: () => ApiAdminLoginRoute,
  } as any)
const ApiAccountLoginSocialCompleteRoute =
  ApiAccountLoginSocialCompleteRouteImport.update({
    id: '/social/complete',
    path: '/social/complete',
    getParentRoute: () => ApiAccountLoginRoute,
  } as any)
const ApiAccountLoginProviderStartRoute =
  ApiAccountLoginProviderStartRouteImport.update({
    id: '/$provider/start',
    path: '/$provider/start',
    getParentRoute: () => ApiAccountLoginRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/admin/assets': typeof AuthAdminAssetsRoute
  '/admin/comments': typeof AuthAdminCommentsRoute
  '/admin/posts': typeof AuthAdminPostsRouteWithChildren
  '/admin/series': typeof AuthAdminSeriesRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/api/account/email-preferences': typeof ApiAccountEmailPreferencesRoute
  '/api/account/login': typeof ApiAccountLoginRouteWithChildren
  '/api/account/logout': typeof ApiAccountLogoutRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/password-reset': typeof ApiAccountPasswordResetRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verification-email': typeof ApiAccountVerificationEmailRoute
  '/api/admin/ai-settings': typeof ApiAdminAiSettingsRouteWithChildren
  '/api/admin/email-broadcasts': typeof ApiAdminEmailBroadcastsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRouteWithChildren
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/api/series/$id': typeof ApiSeriesIdRoute
  '/api/sync/obsidian': typeof ApiSyncObsidianRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/app/': typeof AuthAppIndexRoute
  '/admin/posts/$postId': typeof AuthAdminPostsPostIdRoute
  '/admin/posts/new': typeof AuthAdminPostsNewRoute
  '/api/admin/ai-settings/api-key': typeof ApiAdminAiSettingsApiKeyRoute
  '/api/admin/ai-settings/test': typeof ApiAdminAiSettingsTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comment-auth/google/start': typeof ApiCommentAuthGoogleStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
  '/admin/posts/': typeof AuthAdminPostsIndexRoute
  '/api/account/login/$provider/start': typeof ApiAccountLoginProviderStartRoute
  '/api/account/login/social/complete': typeof ApiAccountLoginSocialCompleteRoute
  '/api/admin/login/$provider/start': typeof ApiAdminLoginProviderStartRoute
  '/api/admin/login/social/complete': typeof ApiAdminLoginSocialCompleteRoute
  '/api/admin/users/$id/password-reset': typeof ApiAdminUsersIdPasswordResetRoute
  '/api/admin/users/$id/sessions': typeof ApiAdminUsersIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/series': typeof SeriesIndexRoute
  '/tags': typeof TagsIndexRoute
  '/admin/assets': typeof AuthAdminAssetsRoute
  '/admin/comments': typeof AuthAdminCommentsRoute
  '/admin/series': typeof AuthAdminSeriesRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/api/account/email-preferences': typeof ApiAccountEmailPreferencesRoute
  '/api/account/login': typeof ApiAccountLoginRouteWithChildren
  '/api/account/logout': typeof ApiAccountLogoutRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/password-reset': typeof ApiAccountPasswordResetRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verification-email': typeof ApiAccountVerificationEmailRoute
  '/api/admin/ai-settings': typeof ApiAdminAiSettingsRouteWithChildren
  '/api/admin/email-broadcasts': typeof ApiAdminEmailBroadcastsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRouteWithChildren
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/api/series/$id': typeof ApiSeriesIdRoute
  '/api/sync/obsidian': typeof ApiSyncObsidianRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/admin': typeof AuthAdminIndexRoute
  '/app': typeof AuthAppIndexRoute
  '/admin/posts/$postId': typeof AuthAdminPostsPostIdRoute
  '/admin/posts/new': typeof AuthAdminPostsNewRoute
  '/api/admin/ai-settings/api-key': typeof ApiAdminAiSettingsApiKeyRoute
  '/api/admin/ai-settings/test': typeof ApiAdminAiSettingsTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comment-auth/google/start': typeof ApiCommentAuthGoogleStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
  '/admin/posts': typeof AuthAdminPostsIndexRoute
  '/api/account/login/$provider/start': typeof ApiAccountLoginProviderStartRoute
  '/api/account/login/social/complete': typeof ApiAccountLoginSocialCompleteRoute
  '/api/admin/login/$provider/start': typeof ApiAdminLoginProviderStartRoute
  '/api/admin/login/social/complete': typeof ApiAdminLoginSocialCompleteRoute
  '/api/admin/users/$id/password-reset': typeof ApiAdminUsersIdPasswordResetRoute
  '/api/admin/users/$id/sessions': typeof ApiAdminUsersIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/backups': typeof ApiBackupsRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/site': typeof ApiSiteRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/_auth/admin/assets': typeof AuthAdminAssetsRoute
  '/_auth/admin/comments': typeof AuthAdminCommentsRoute
  '/_auth/admin/posts': typeof AuthAdminPostsRouteWithChildren
  '/_auth/admin/series': typeof AuthAdminSeriesRoute
  '/_auth/admin/settings': typeof AuthAdminSettingsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/api/account/email-preferences': typeof ApiAccountEmailPreferencesRoute
  '/api/account/login': typeof ApiAccountLoginRouteWithChildren
  '/api/account/logout': typeof ApiAccountLogoutRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/password-reset': typeof ApiAccountPasswordResetRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verification-email': typeof ApiAccountVerificationEmailRoute
  '/api/admin/ai-settings': typeof ApiAdminAiSettingsRouteWithChildren
  '/api/admin/email-broadcasts': typeof ApiAdminEmailBroadcastsRoute
  '/api/admin/email-status': typeof ApiAdminEmailStatusRoute
  '/api/admin/login': typeof ApiAdminLoginRouteWithChildren
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/password': typeof ApiAdminPasswordRoute
  '/api/admin/password-reset': typeof ApiAdminPasswordResetRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comment-auth/login': typeof ApiCommentAuthLoginRoute
  '/api/comment-auth/logout': typeof ApiCommentAuthLogoutRoute
  '/api/comment-auth/me': typeof ApiCommentAuthMeRoute
  '/api/comment-auth/signup': typeof ApiCommentAuthSignupRoute
  '/api/comment-auth/verify-email': typeof ApiCommentAuthVerifyEmailRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/import/html': typeof ApiImportHtmlRoute
  '/api/import/markdown': typeof ApiImportMarkdownRoute
  '/api/import/zip': typeof ApiImportZipRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/posts/batch': typeof ApiPostsBatchRoute
  '/api/series/$id': typeof ApiSeriesIdRoute
  '/api/sync/obsidian': typeof ApiSyncObsidianRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/admin/posts/$postId': typeof AuthAdminPostsPostIdRoute
  '/_auth/admin/posts/new': typeof AuthAdminPostsNewRoute
  '/api/admin/ai-settings/api-key': typeof ApiAdminAiSettingsApiKeyRoute
  '/api/admin/ai-settings/test': typeof ApiAdminAiSettingsTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/comment-auth/github/start': typeof ApiCommentAuthGithubStartRoute
  '/api/comment-auth/google/start': typeof ApiCommentAuthGoogleStartRoute
  '/api/comments/$id/approve': typeof ApiCommentsIdApproveRoute
  '/api/comments/$id/delete': typeof ApiCommentsIdDeleteRoute
  '/api/comments/$id/spam': typeof ApiCommentsIdSpamRoute
  '/api/tokens/$id/revoke': typeof ApiTokensIdRevokeRoute
  '/_auth/admin/posts/': typeof AuthAdminPostsIndexRoute
  '/api/account/login/$provider/start': typeof ApiAccountLoginProviderStartRoute
  '/api/account/login/social/complete': typeof ApiAccountLoginSocialCompleteRoute
  '/api/admin/login/$provider/start': typeof ApiAdminLoginProviderStartRoute
  '/api/admin/login/social/complete': typeof ApiAdminLoginSocialCompleteRoute
  '/api/admin/users/$id/password-reset': typeof ApiAdminUsersIdPasswordResetRoute
  '/api/admin/users/$id/sessions': typeof ApiAdminUsersIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/posts'
    | '/api/search'
    | '/api/series'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/series/$slug'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog/'
    | '/series/'
    | '/tags/'
    | '/admin/assets'
    | '/admin/comments'
    | '/admin/posts'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/users'
    | '/api/account/email-preferences'
    | '/api/account/login'
    | '/api/account/logout'
    | '/api/account/me'
    | '/api/account/password'
    | '/api/account/password-reset'
    | '/api/account/profile'
    | '/api/account/signup'
    | '/api/account/verification-email'
    | '/api/admin/ai-settings'
    | '/api/admin/email-broadcasts'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/analytics/overview'
    | '/api/analytics/track'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/email/unsubscribe'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/api/series/$id'
    | '/api/sync/obsidian'
    | '/zh/docs/$'
    | '/admin/'
    | '/app/'
    | '/admin/posts/$postId'
    | '/admin/posts/new'
    | '/api/admin/ai-settings/api-key'
    | '/api/admin/ai-settings/test'
    | '/api/admin/users/$id'
    | '/api/comment-auth/github/start'
    | '/api/comment-auth/google/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
    | '/admin/posts/'
    | '/api/account/login/$provider/start'
    | '/api/account/login/social/complete'
    | '/api/admin/login/$provider/start'
    | '/api/admin/login/social/complete'
    | '/api/admin/users/$id/password-reset'
    | '/api/admin/users/$id/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/posts'
    | '/api/search'
    | '/api/series'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/series/$slug'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog'
    | '/series'
    | '/tags'
    | '/admin/assets'
    | '/admin/comments'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/users'
    | '/api/account/email-preferences'
    | '/api/account/login'
    | '/api/account/logout'
    | '/api/account/me'
    | '/api/account/password'
    | '/api/account/password-reset'
    | '/api/account/profile'
    | '/api/account/signup'
    | '/api/account/verification-email'
    | '/api/admin/ai-settings'
    | '/api/admin/email-broadcasts'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/analytics/overview'
    | '/api/analytics/track'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/email/unsubscribe'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/api/series/$id'
    | '/api/sync/obsidian'
    | '/zh/docs/$'
    | '/admin'
    | '/app'
    | '/admin/posts/$postId'
    | '/admin/posts/new'
    | '/api/admin/ai-settings/api-key'
    | '/api/admin/ai-settings/test'
    | '/api/admin/users/$id'
    | '/api/comment-auth/github/start'
    | '/api/comment-auth/google/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
    | '/admin/posts'
    | '/api/account/login/$provider/start'
    | '/api/account/login/social/complete'
    | '/api/admin/login/$provider/start'
    | '/api/admin/login/social/complete'
    | '/api/admin/users/$id/password-reset'
    | '/api/admin/users/$id/sessions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/about'
    | '/demo'
    | '/feed.xml'
    | '/openapi.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-posts.xml'
    | '/sitemap.xml'
    | '/_auth/admin'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_guest/signup'
    | '/api/assets'
    | '/api/backups'
    | '/api/comments'
    | '/api/export'
    | '/api/posts'
    | '/api/search'
    | '/api/series'
    | '/api/site'
    | '/api/tokens'
    | '/blog/$slug'
    | '/docs/$'
    | '/series/$slug'
    | '/tags/$slug'
    | '/uploads/$'
    | '/blog/'
    | '/series/'
    | '/tags/'
    | '/_auth/admin/assets'
    | '/_auth/admin/comments'
    | '/_auth/admin/posts'
    | '/_auth/admin/series'
    | '/_auth/admin/settings'
    | '/_auth/admin/users'
    | '/api/account/email-preferences'
    | '/api/account/login'
    | '/api/account/logout'
    | '/api/account/me'
    | '/api/account/password'
    | '/api/account/password-reset'
    | '/api/account/profile'
    | '/api/account/signup'
    | '/api/account/verification-email'
    | '/api/admin/ai-settings'
    | '/api/admin/email-broadcasts'
    | '/api/admin/email-status'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/password'
    | '/api/admin/password-reset'
    | '/api/admin/users'
    | '/api/analytics/overview'
    | '/api/analytics/track'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/comment-auth/login'
    | '/api/comment-auth/logout'
    | '/api/comment-auth/me'
    | '/api/comment-auth/signup'
    | '/api/comment-auth/verify-email'
    | '/api/email/unsubscribe'
    | '/api/import/html'
    | '/api/import/markdown'
    | '/api/import/zip'
    | '/api/posts/$id'
    | '/api/posts/batch'
    | '/api/series/$id'
    | '/api/sync/obsidian'
    | '/zh/docs/$'
    | '/_auth/admin/'
    | '/_auth/app/'
    | '/_auth/admin/posts/$postId'
    | '/_auth/admin/posts/new'
    | '/api/admin/ai-settings/api-key'
    | '/api/admin/ai-settings/test'
    | '/api/admin/users/$id'
    | '/api/comment-auth/github/start'
    | '/api/comment-auth/google/start'
    | '/api/comments/$id/approve'
    | '/api/comments/$id/delete'
    | '/api/comments/$id/spam'
    | '/api/tokens/$id/revoke'
    | '/_auth/admin/posts/'
    | '/api/account/login/$provider/start'
    | '/api/account/login/social/complete'
    | '/api/admin/login/$provider/start'
    | '/api/admin/login/social/complete'
    | '/api/admin/users/$id/password-reset'
    | '/api/admin/users/$id/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapPostsDotxmlRoute: typeof SitemapPostsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAssetsRoute: typeof ApiAssetsRouteWithChildren
  ApiBackupsRoute: typeof ApiBackupsRoute
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSeriesRoute: typeof ApiSeriesRouteWithChildren
  ApiSiteRoute: typeof ApiSiteRoute
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ApiAccountEmailPreferencesRoute: typeof ApiAccountEmailPreferencesRoute
  ApiAccountLoginRoute: typeof ApiAccountLoginRouteWithChildren
  ApiAccountLogoutRoute: typeof ApiAccountLogoutRoute
  ApiAccountMeRoute: typeof ApiAccountMeRoute
  ApiAccountPasswordRoute: typeof ApiAccountPasswordRoute
  ApiAccountPasswordResetRoute: typeof ApiAccountPasswordResetRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAccountSignupRoute: typeof ApiAccountSignupRoute
  ApiAccountVerificationEmailRoute: typeof ApiAccountVerificationEmailRoute
  ApiAdminAiSettingsRoute: typeof ApiAdminAiSettingsRouteWithChildren
  ApiAdminEmailBroadcastsRoute: typeof ApiAdminEmailBroadcastsRoute
  ApiAdminEmailStatusRoute: typeof ApiAdminEmailStatusRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRouteWithChildren
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminPasswordRoute: typeof ApiAdminPasswordRoute
  ApiAdminPasswordResetRoute: typeof ApiAdminPasswordResetRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAnalyticsOverviewRoute: typeof ApiAnalyticsOverviewRoute
  ApiAnalyticsTrackRoute: typeof ApiAnalyticsTrackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommentAuthLoginRoute: typeof ApiCommentAuthLoginRoute
  ApiCommentAuthLogoutRoute: typeof ApiCommentAuthLogoutRoute
  ApiCommentAuthMeRoute: typeof ApiCommentAuthMeRoute
  ApiCommentAuthSignupRoute: typeof ApiCommentAuthSignupRoute
  ApiCommentAuthVerifyEmailRoute: typeof ApiCommentAuthVerifyEmailRoute
  ApiEmailUnsubscribeRoute: typeof ApiEmailUnsubscribeRoute
  ApiImportHtmlRoute: typeof ApiImportHtmlRoute
  ApiImportMarkdownRoute: typeof ApiImportMarkdownRoute
  ApiImportZipRoute: typeof ApiImportZipRoute
  ApiSyncObsidianRoute: typeof ApiSyncObsidianRoute
  ZhDocsSplatRoute: typeof ZhDocsSplatRoute
  ApiCommentAuthGithubStartRoute: typeof ApiCommentAuthGithubStartRoute
  ApiCommentAuthGoogleStartRoute: typeof ApiCommentAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-posts.xml': {
      id: '/sitemap-posts.xml'
      path: '/sitemap-posts.xml'
      fullPath: '/sitemap-posts.xml'
      preLoaderRoute: typeof SitemapPostsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site': {
      id: '/api/site'
      path: '/api/site'
      fullPath: '/api/site'
      preLoaderRoute: typeof ApiSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backups': {
      id: '/api/backups'
      path: '/api/backups'
      fullPath: '/api/backups'
      preLoaderRoute: typeof ApiBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/zh/docs/$': {
      id: '/zh/docs/$'
      path: '/zh/docs/$'
      fullPath: '/zh/docs/$'
      preLoaderRoute: typeof ZhDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/obsidian': {
      id: '/api/sync/obsidian'
      path: '/api/sync/obsidian'
      fullPath: '/api/sync/obsidian'
      preLoaderRoute: typeof ApiSyncObsidianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series/$id': {
      id: '/api/series/$id'
      path: '/$id'
      fullPath: '/api/series/$id'
      preLoaderRoute: typeof ApiSeriesIdRouteImport
      parentRoute: typeof ApiSeriesRoute
    }
    '/api/posts/batch': {
      id: '/api/posts/batch'
      path: '/batch'
      fullPath: '/api/posts/batch'
      preLoaderRoute: typeof ApiPostsBatchRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/import/zip': {
      id: '/api/import/zip'
      path: '/api/import/zip'
      fullPath: '/api/import/zip'
      preLoaderRoute: typeof ApiImportZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/markdown': {
      id: '/api/import/markdown'
      path: '/api/import/markdown'
      fullPath: '/api/import/markdown'
      preLoaderRoute: typeof ApiImportMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/html': {
      id: '/api/import/html'
      path: '/api/import/html'
      fullPath: '/api/import/html'
      preLoaderRoute: typeof ApiImportHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/unsubscribe': {
      id: '/api/email/unsubscribe'
      path: '/api/email/unsubscribe'
      fullPath: '/api/email/unsubscribe'
      preLoaderRoute: typeof ApiEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/verify-email': {
      id: '/api/comment-auth/verify-email'
      path: '/api/comment-auth/verify-email'
      fullPath: '/api/comment-auth/verify-email'
      preLoaderRoute: typeof ApiCommentAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/signup': {
      id: '/api/comment-auth/signup'
      path: '/api/comment-auth/signup'
      fullPath: '/api/comment-auth/signup'
      preLoaderRoute: typeof ApiCommentAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/me': {
      id: '/api/comment-auth/me'
      path: '/api/comment-auth/me'
      fullPath: '/api/comment-auth/me'
      preLoaderRoute: typeof ApiCommentAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/logout': {
      id: '/api/comment-auth/logout'
      path: '/api/comment-auth/logout'
      fullPath: '/api/comment-auth/logout'
      preLoaderRoute: typeof ApiCommentAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/login': {
      id: '/api/comment-auth/login'
      path: '/api/comment-auth/login'
      fullPath: '/api/comment-auth/login'
      preLoaderRoute: typeof ApiCommentAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdRouteImport
      parentRoute: typeof ApiAssetsRoute
    }
    '/api/analytics/track': {
      id: '/api/analytics/track'
      path: '/api/analytics/track'
      fullPath: '/api/analytics/track'
      preLoaderRoute: typeof ApiAnalyticsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/overview': {
      id: '/api/analytics/overview'
      path: '/api/analytics/overview'
      fullPath: '/api/analytics/overview'
      preLoaderRoute: typeof ApiAnalyticsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password-reset': {
      id: '/api/admin/password-reset'
      path: '/api/admin/password-reset'
      fullPath: '/api/admin/password-reset'
      preLoaderRoute: typeof ApiAdminPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password': {
      id: '/api/admin/password'
      path: '/api/admin/password'
      fullPath: '/api/admin/password'
      preLoaderRoute: typeof ApiAdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-status': {
      id: '/api/admin/email-status'
      path: '/api/admin/email-status'
      fullPath: '/api/admin/email-status'
      preLoaderRoute: typeof ApiAdminEmailStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-broadcasts': {
      id: '/api/admin/email-broadcasts'
      path: '/api/admin/email-broadcasts'
      fullPath: '/api/admin/email-broadcasts'
      preLoaderRoute: typeof ApiAdminEmailBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai-settings': {
      id: '/api/admin/ai-settings'
      path: '/api/admin/ai-settings'
      fullPath: '/api/admin/ai-settings'
      preLoaderRoute: typeof ApiAdminAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/verification-email': {
      id: '/api/account/verification-email'
      path: '/api/account/verification-email'
      fullPath: '/api/account/verification-email'
      preLoaderRoute: typeof ApiAccountVerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/signup': {
      id: '/api/account/signup'
      path: '/api/account/signup'
      fullPath: '/api/account/signup'
      preLoaderRoute: typeof ApiAccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/password-reset': {
      id: '/api/account/password-reset'
      path: '/api/account/password-reset'
      fullPath: '/api/account/password-reset'
      preLoaderRoute: typeof ApiAccountPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/password': {
      id: '/api/account/password'
      path: '/api/account/password'
      fullPath: '/api/account/password'
      preLoaderRoute: typeof ApiAccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/me': {
      id: '/api/account/me'
      path: '/api/account/me'
      fullPath: '/api/account/me'
      preLoaderRoute: typeof ApiAccountMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/logout': {
      id: '/api/account/logout'
      path: '/api/account/logout'
      fullPath: '/api/account/logout'
      preLoaderRoute: typeof ApiAccountLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/login': {
      id: '/api/account/login'
      path: '/api/account/login'
      fullPath: '/api/account/login'
      preLoaderRoute: typeof ApiAccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/email-preferences': {
      id: '/api/account/email-preferences'
      path: '/api/account/email-preferences'
      fullPath: '/api/account/email-preferences'
      preLoaderRoute: typeof ApiAccountEmailPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/settings': {
      id: '/_auth/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/series': {
      id: '/_auth/admin/series'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AuthAdminSeriesRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/posts': {
      id: '/_auth/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthAdminPostsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/comments': {
      id: '/_auth/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthAdminCommentsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/assets': {
      id: '/_auth/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthAdminAssetsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/posts/': {
      id: '/_auth/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthAdminPostsIndexRouteImport
      parentRoute: typeof AuthAdminPostsRoute
    }
    '/api/tokens/$id/revoke': {
      id: '/api/tokens/$id/revoke'
      path: '/$id/revoke'
      fullPath: '/api/tokens/$id/revoke'
      preLoaderRoute: typeof ApiTokensIdRevokeRouteImport
      parentRoute: typeof ApiTokensRoute
    }
    '/api/comments/$id/spam': {
      id: '/api/comments/$id/spam'
      path: '/$id/spam'
      fullPath: '/api/comments/$id/spam'
      preLoaderRoute: typeof ApiCommentsIdSpamRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/$id/delete': {
      id: '/api/comments/$id/delete'
      path: '/$id/delete'
      fullPath: '/api/comments/$id/delete'
      preLoaderRoute: typeof ApiCommentsIdDeleteRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/$id/approve': {
      id: '/api/comments/$id/approve'
      path: '/$id/approve'
      fullPath: '/api/comments/$id/approve'
      preLoaderRoute: typeof ApiCommentsIdApproveRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comment-auth/google/start': {
      id: '/api/comment-auth/google/start'
      path: '/api/comment-auth/google/start'
      fullPath: '/api/comment-auth/google/start'
      preLoaderRoute: typeof ApiCommentAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-auth/github/start': {
      id: '/api/comment-auth/github/start'
      path: '/api/comment-auth/github/start'
      fullPath: '/api/comment-auth/github/start'
      preLoaderRoute: typeof ApiCommentAuthGithubStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/ai-settings/test': {
      id: '/api/admin/ai-settings/test'
      path: '/test'
      fullPath: '/api/admin/ai-settings/test'
      preLoaderRoute: typeof ApiAdminAiSettingsTestRouteImport
      parentRoute: typeof ApiAdminAiSettingsRoute
    }
    '/api/admin/ai-settings/api-key': {
      id: '/api/admin/ai-settings/api-key'
      path: '/api-key'
      fullPath: '/api/admin/ai-settings/api-key'
      preLoaderRoute: typeof ApiAdminAiSettingsApiKeyRouteImport
      parentRoute: typeof ApiAdminAiSettingsRoute
    }
    '/_auth/admin/posts/new': {
      id: '/_auth/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AuthAdminPostsNewRouteImport
      parentRoute: typeof AuthAdminPostsRoute
    }
    '/_auth/admin/posts/$postId': {
      id: '/_auth/admin/posts/$postId'
      path: '/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AuthAdminPostsPostIdRouteImport
      parentRoute: typeof AuthAdminPostsRoute
    }
    '/api/admin/users/$id/sessions': {
      id: '/api/admin/users/$id/sessions'
      path: '/sessions'
      fullPath: '/api/admin/users/$id/sessions'
      preLoaderRoute: typeof ApiAdminUsersIdSessionsRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/password-reset': {
      id: '/api/admin/users/$id/password-reset'
      path: '/password-reset'
      fullPath: '/api/admin/users/$id/password-reset'
      preLoaderRoute: typeof ApiAdminUsersIdPasswordResetRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/login/social/complete': {
      id: '/api/admin/login/social/complete'
      path: '/social/complete'
      fullPath: '/api/admin/login/social/complete'
      preLoaderRoute: typeof ApiAdminLoginSocialCompleteRouteImport
      parentRoute: typeof ApiAdminLoginRoute
    }
    '/api/admin/login/$provider/start': {
      id: '/api/admin/login/$provider/start'
      path: '/$provider/start'
      fullPath: '/api/admin/login/$provider/start'
      preLoaderRoute: typeof ApiAdminLoginProviderStartRouteImport
      parentRoute: typeof ApiAdminLoginRoute
    }
    '/api/account/login/social/complete': {
      id: '/api/account/login/social/complete'
      path: '/social/complete'
      fullPath: '/api/account/login/social/complete'
      preLoaderRoute: typeof ApiAccountLoginSocialCompleteRouteImport
      parentRoute: typeof ApiAccountLoginRoute
    }
    '/api/account/login/$provider/start': {
      id: '/api/account/login/$provider/start'
      path: '/$provider/start'
      fullPath: '/api/account/login/$provider/start'
      preLoaderRoute: typeof ApiAccountLoginProviderStartRouteImport
      parentRoute: typeof ApiAccountLoginRoute
    }
  }
}

interface AuthAdminPostsRouteChildren {
  AuthAdminPostsPostIdRoute: typeof AuthAdminPostsPostIdRoute
  AuthAdminPostsNewRoute: typeof AuthAdminPostsNewRoute
  AuthAdminPostsIndexRoute: typeof AuthAdminPostsIndexRoute
}

const AuthAdminPostsRouteChildren: AuthAdminPostsRouteChildren = {
  AuthAdminPostsPostIdRoute: AuthAdminPostsPostIdRoute,
  AuthAdminPostsNewRoute: AuthAdminPostsNewRoute,
  AuthAdminPostsIndexRoute: AuthAdminPostsIndexRoute,
}

const AuthAdminPostsRouteWithChildren = AuthAdminPostsRoute._addFileChildren(
  AuthAdminPostsRouteChildren,
)

interface AuthAdminRouteRouteChildren {
  AuthAdminAssetsRoute: typeof AuthAdminAssetsRoute
  AuthAdminCommentsRoute: typeof AuthAdminCommentsRoute
  AuthAdminPostsRoute: typeof AuthAdminPostsRouteWithChildren
  AuthAdminSeriesRoute: typeof AuthAdminSeriesRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminAssetsRoute: AuthAdminAssetsRoute,
  AuthAdminCommentsRoute: AuthAdminCommentsRoute,
  AuthAdminPostsRoute: AuthAdminPostsRouteWithChildren,
  AuthAdminSeriesRoute: AuthAdminSeriesRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiAssetsRouteChildren {
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
}

const ApiAssetsRouteChildren: ApiAssetsRouteChildren = {
  ApiAssetsIdRoute: ApiAssetsIdRoute,
}

const ApiAssetsRouteWithChildren = ApiAssetsRoute._addFileChildren(
  ApiAssetsRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsIdApproveRoute: typeof ApiCommentsIdApproveRoute
  ApiCommentsIdDeleteRoute: typeof ApiCommentsIdDeleteRoute
  ApiCommentsIdSpamRoute: typeof ApiCommentsIdSpamRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsIdApproveRoute: ApiCommentsIdApproveRoute,
  ApiCommentsIdDeleteRoute: ApiCommentsIdDeleteRoute,
  ApiCommentsIdSpamRoute: ApiCommentsIdSpamRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiPostsRouteChildren {
  ApiPostsIdRoute: typeof ApiPostsIdRoute
  ApiPostsBatchRoute: typeof ApiPostsBatchRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsIdRoute: ApiPostsIdRoute,
  ApiPostsBatchRoute: ApiPostsBatchRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

interface ApiSeriesRouteChildren {
  ApiSeriesIdRoute: typeof ApiSeriesIdRoute
}

const ApiSeriesRouteChildren: ApiSeriesRouteChildren = {
  ApiSeriesIdRoute: ApiSeriesIdRoute,
}

const ApiSeriesRouteWithChildren = ApiSeriesRoute._addFileChildren(
  ApiSeriesRouteChildren,
)

interface ApiTokensRouteChildren {
  ApiTokensIdRevokeRoute: typeof ApiTokensIdRevokeRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensIdRevokeRoute: ApiTokensIdRevokeRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

interface ApiAccountLoginRouteChildren {
  ApiAccountLoginProviderStartRoute: typeof ApiAccountLoginProviderStartRoute
  ApiAccountLoginSocialCompleteRoute: typeof ApiAccountLoginSocialCompleteRoute
}

const ApiAccountLoginRouteChildren: ApiAccountLoginRouteChildren = {
  ApiAccountLoginProviderStartRoute: ApiAccountLoginProviderStartRoute,
  ApiAccountLoginSocialCompleteRoute: ApiAccountLoginSocialCompleteRoute,
}

const ApiAccountLoginRouteWithChildren = ApiAccountLoginRoute._addFileChildren(
  ApiAccountLoginRouteChildren,
)

interface ApiAdminAiSettingsRouteChildren {
  ApiAdminAiSettingsApiKeyRoute: typeof ApiAdminAiSettingsApiKeyRoute
  ApiAdminAiSettingsTestRoute: typeof ApiAdminAiSettingsTestRoute
}

const ApiAdminAiSettingsRouteChildren: ApiAdminAiSettingsRouteChildren = {
  ApiAdminAiSettingsApiKeyRoute: ApiAdminAiSettingsApiKeyRoute,
  ApiAdminAiSettingsTestRoute: ApiAdminAiSettingsTestRoute,
}

const ApiAdminAiSettingsRouteWithChildren =
  ApiAdminAiSettingsRoute._addFileChildren(ApiAdminAiSettingsRouteChildren)

interface ApiAdminLoginRouteChildren {
  ApiAdminLoginProviderStartRoute: typeof ApiAdminLoginProviderStartRoute
  ApiAdminLoginSocialCompleteRoute: typeof ApiAdminLoginSocialCompleteRoute
}

const ApiAdminLoginRouteChildren: ApiAdminLoginRouteChildren = {
  ApiAdminLoginProviderStartRoute: ApiAdminLoginProviderStartRoute,
  ApiAdminLoginSocialCompleteRoute: ApiAdminLoginSocialCompleteRoute,
}

const ApiAdminLoginRouteWithChildren = ApiAdminLoginRoute._addFileChildren(
  ApiAdminLoginRouteChildren,
)

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdPasswordResetRoute: typeof ApiAdminUsersIdPasswordResetRoute
  ApiAdminUsersIdSessionsRoute: typeof ApiAdminUsersIdSessionsRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdPasswordResetRoute: ApiAdminUsersIdPasswordResetRoute,
  ApiAdminUsersIdSessionsRoute: ApiAdminUsersIdSessionsRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapPostsDotxmlRoute: SitemapPostsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAssetsRoute: ApiAssetsRouteWithChildren,
  ApiBackupsRoute: ApiBackupsRoute,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSeriesRoute: ApiSeriesRouteWithChildren,
  ApiSiteRoute: ApiSiteRoute,
  ApiTokensRoute: ApiTokensRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  ApiAccountEmailPreferencesRoute: ApiAccountEmailPreferencesRoute,
  ApiAccountLoginRoute: ApiAccountLoginRouteWithChildren,
  ApiAccountLogoutRoute: ApiAccountLogoutRoute,
  ApiAccountMeRoute: ApiAccountMeRoute,
  ApiAccountPasswordRoute: ApiAccountPasswordRoute,
  ApiAccountPasswordResetRoute: ApiAccountPasswordResetRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAccountSignupRoute: ApiAccountSignupRoute,
  ApiAccountVerificationEmailRoute: ApiAccountVerificationEmailRoute,
  ApiAdminAiSettingsRoute: ApiAdminAiSettingsRouteWithChildren,
  ApiAdminEmailBroadcastsRoute: ApiAdminEmailBroadcastsRoute,
  ApiAdminEmailStatusRoute: ApiAdminEmailStatusRoute,
  ApiAdminLoginRoute: ApiAdminLoginRouteWithChildren,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminPasswordRoute: ApiAdminPasswordRoute,
  ApiAdminPasswordResetRoute: ApiAdminPasswordResetRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAnalyticsOverviewRoute: ApiAnalyticsOverviewRoute,
  ApiAnalyticsTrackRoute: ApiAnalyticsTrackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommentAuthLoginRoute: ApiCommentAuthLoginRoute,
  ApiCommentAuthLogoutRoute: ApiCommentAuthLogoutRoute,
  ApiCommentAuthMeRoute: ApiCommentAuthMeRoute,
  ApiCommentAuthSignupRoute: ApiCommentAuthSignupRoute,
  ApiCommentAuthVerifyEmailRoute: ApiCommentAuthVerifyEmailRoute,
  ApiEmailUnsubscribeRoute: ApiEmailUnsubscribeRoute,
  ApiImportHtmlRoute: ApiImportHtmlRoute,
  ApiImportMarkdownRoute: ApiImportMarkdownRoute,
  ApiImportZipRoute: ApiImportZipRoute,
  ApiSyncObsidianRoute: ApiSyncObsidianRoute,
  ZhDocsSplatRoute: ZhDocsSplatRoute,
  ApiCommentAuthGithubStartRoute: ApiCommentAuthGithubStartRoute,
  ApiCommentAuthGoogleStartRoute: ApiCommentAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
